= BUT Info Blagnac
:website: https://IUT-Blagnac.github.io/but
:baseURL: https://github.com/charlotte78000/but
// Specific to GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

//------------------------------------ Badges --------
image:{baseURL}/actions/workflows/check.yml/badge.svg[Test] 
image:{baseURL}/actions/workflows/main.yml/badge.svg[Déploiement] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//------------------------------------ Badges --------

CAUTION: Site en construction!! 

Site pour la description du BUT Informatique de l'IUT de Blagnac.

La version déployée (automatiquement) de ce site est ici : {website}.


== Informations

=== Pages

Pour ajouter une page, aller au niveau du répertoire concerné et l'enregistrer dans le fichier 
`nav.adoc` 

associé de la manière suivante:

    xref:page.adoc 


=== Images

Pour stocker les images dans le répertoire but, aller au niveau du répertoire concerné dans le dossier
 `images`.

Pour stocker les images dans le répertoire ui, enregister l'image sous le format `svg` dans le dossier `src`.

=== Liens

Pour créer un lien vers une page procédez ainsi : `xref:nom_du_répertoire:page.adoc`

Pour afficher une image dans une page procédez ainsi :

    image:nom_du_sous_répertoire:image.ext[]

Pour créer un lien sur une image pour présenter les liens entre modules procédez ainsi :

    image:image.ext[xref=nom_du_repertoire:page.adoc]


=== PDF

Pour ajouter un fichier pdf, aller dans ROOT et l'enregister dans le dossier `pages` ainsi que le répertoire sae au niveau du dossier `attachments`.
Aller au niveau du répertoire sae et enregister le lien du pdf dans le fichier `pdf.adoc` de la manière suivante : 
    
    xref:attachment$nom_du_fichier.pdf[] 

Dans le partie interface utilisateur, créer un lien vers le pdf dans le fichier concerné de la manière suivante: 
    `href="pdf.html"`