= BUT Info Blagnac
:website: https://IUT-Blagnac.github.io/but
:baseURL: https://github.com/IUT-Blagnac/but
// Specific to GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

//------------------------------------ Badges --------
image:{baseURL}/actions/workflows/check.yml/badge.svg[Test] 
image:{baseURL}/actions/workflows/main.yml/badge.svg[Déploiement] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//------------------------------------ Badges --------

CAUTION: Site en construction!! 

Site pour la description du BUT Informatique de l'IUT de Blagnac.

La version déployée (automatiquement) de ce site est ici : {website}.


.*Informations*

- *Pages*

Ajouter une page dans modules/répertoire et l'enregistrer dans répertoire/nav.adoc de la manière suivante:
<xref:page.adoc>

- *Images*

Stocker les images dans modules/repertoire/images/sous_répertoire

- *Liens*

    Pour créer un lien vers une page procédez ainsi : <xref:nom_du_répertoire:page.adoc>

    Pour afficher une image dans une page procédez ainsi : <xref:nom_du_sous_répertoire:image.ext>

    Pour créer un lien sur une image pour présenter les liens entre modules procédez ainsi : <xref:nom_du_répertoire>